### ISSUE TITLE
Can we change the recommendation against @license_type?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/JATS4R-Participant-Hub#108]
This suggestion actually came from @hubgit , via email.

There are a *lot* of articles that use `@license_type`, and it seems to me that as long as we say that machines should ignore it, the presence or absence of it doesn't do any harm.

So, I'd like to suggest that we change this into an info, or at least a warning message, instead of error.

**Comment by jeffbeckncbi** [comment]
I think a warning or error would be correct here. As long as users know that JATS4R is not expecting any machines to make any decisions based on it.

**Comment by Klortho** [comment]
Hmm. I still really think it should only be an info. Here's the peerj example:

```xml
<license license-type="open-access" xlink:href="http://creativecommons.org/licenses/by/4.0/">...
```

As long as bot developers know that they should ignore this attribute, what harm does it do? On the other hand, some workflows might still use it, and it would be a shame to add extraneous warnings to a content provider's validation output.

Maybe we can take a vote or something?

**Comment by hubgit** [comment]
We've actually removed the `license-type` attribute from PeerJ's XML, so the example needs updating. :smile:

**Comment by vincentml** [comment]
The recommendations currently state: 

> The attribute @license-type for <license> is not machine readable and therefore should not be used.

license@license-type="open-access" is machine readable, and using this attribute to identify open access is probably fairly common. The trouble with it is that this attribute is not able to convey specific information about the license.

I'd suggest removing this sentence and adding it it's place a recommendation that <license license-type="open-access"> can be used to indicate an article is Open Access but more specific information about the license should be included, possibly as a xlink:href to the license or a textual description of the license in <license-p>.

**Comment by hubgit** [comment]
> using this attribute to identify open access is probably fairly common

Can you point to some of the places where this attribute is used?

**Comment by vincentml** [comment]
Yes. license license-type="open-access" is being used by PMC ([see tagging guidelines](http://preview.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-license)); Atypon; and we are using this at Taylor & Francis.

**Comment by Klortho** [comment]
> license@license-type="open-access" is machine readable

Well, yes, in the sense that you could program a machine to recognize it. But the problem is more than just that it can't convey specific information, but also that the definition of "open access" itself is very controversial. That's why the NISO ALI folks steered clear of using this term.

Okay, I guess I'm okay with making it a warning. @vincentml , are you? We should definitely *also* fix the description of this in the recommendations document.

**Comment by vincentml** [comment]
What would the warning be exactly?

**Comment by jeffbeckncbi** [comment]
The problem with this attribute is that it is not machine-readable and that any value put in there is subject to interpretation - “open-access” being one of the most “interpreted” values I can think of.

We have it in PMC Tagging Guidelines because we get so much content with it supplied. We have no processes that read this attribute in PMC.

I still like
"The attribute @license-type is not machine readable and therefore should not be used.”

But it is a little presumptuous of us to say that and attribute shouldn’t be used just because we don’t have a way for machines to read it. Publishers can put information in there that is specific to their workflow. They just need to understand that no one else can be expected read, understand, or act on the content of that attribute.

Maybe we change it to something like

"The attribute @license-type is not machine readable. If it is used to hold information specific to a publisher’s workflow, secondary users of the content can not be expected to read, understand, or act on it.”

Jeff

**Comment by vincentml** [comment]
I do not like "is not machine readable" because, clearly, it is machine readable. Attribute values are almost always more useful for building machine rules around than, for example, free text in an element.

It is more helpful to state what can be expected, or not expected, from the license-type attribute. The license-type attribute can be used to identify (a subset of) Open Access articles, but it's not descriptive enough to identify what is allowed under an article's license.

**Comment by hubgit** [comment]
> license license-type="open-access" is being used by […] Atypon; and we are using this at Taylor & Francis.

Can you describe what the `license-type="open-access"` attribute is used for, that isn't solved by the use of a license URI in the `href` attribute?

**Comment by vincentml** [comment]
Over time we have used several different licenses, including different versions of Creative Commons licenses, for publishing articles as Open Access. So there are multiple URLs, and not every license has a URL. Identifying Open Access articles based on the URL in the license/@xlink:href attribute would require more effort to maintain and would not work for all licenses. On the other hand, license/@license-type="open-access" is a single assertion that we can use reliably to identify Open Access articles.

**Comment by ostephens** [comment]
When this was discussed last year 'ignore' seemed to be the consensus - see #13
