### ISSUE TITLE
Authors of corrections

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/JATS4R-Participant-Hub#42]
Perhaps not really a JATS question, but I find it odd that journal staff are indicated as authors of this correction, which also makes them authors of the figure and video, which is most likely not correct:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC4320074 .

**Comment by jats-laura** [comment]
I think this a (possibly questionable) publishing decision, not at all a JATS issue.

**Comment by Klortho** [comment]
It's a legitimate JATS4R issue though, since the focus here is on machine-readability. We've talked a lot about how to provide different licenses for different sub-parts of an article. What about different authors?

I see that [&lt;contrib-group>](http://jatspan.org/niso/publishing-1.1d1/#p=elem-contrib-group) is allowed within `<article-meta>, <collab>, <front-stub>, <journal-meta>, <sec-meta>, <supplement>`, but not the great variety of elements that [&lt;permissions](http://jatspan.org/niso/publishing-1.1d1/#p=elem-permissions) is allowed in. For example, it's not allowed within &lt;graphic>. So I don't see how, with the current JATS standard, we could do something similar.

**Comment by jats-laura** [comment]
I would agree that how to capture contributors is a JATS4R issue, but whether or not a publisher chooses to identify authors of a correction (whether it be journal staff, the authors of the original article, or none at all) is a publishing decision. It is not a machine-readability issue.
