### ISSUE TITLE
Author names in italics?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/JATS4R-Participant-Hub#43]
Same example as in #42:
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC4320074 .
It seems odd to me that the content of the contrib tag might need to be set in italics, but I guess there may indeed be special cases like names of consortia, where this would be valid, so just putting this up here to invite other opinions.

**Comment by Klortho** [comment]
Not sure what you're suggesting here -- that we disallow these? 

My opinion is that the contents of these, for both human authors as well as institutions, is not well controlled, and that it would be basically impossible to control tightly enough to ensure machine readability. Rather than try to do that, we should look for ways to include references to established authority databases, like ORCID for authors. I don't know of authority files for institutions, but I'm sure they exist.
