### ISSUE TITLE
How to mark up F1000Research licenses?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/JATS4R-Participant-Hub#45]
Going over our old "Inconsistent XML" paper just now, I came across the example from F1000Research, which makes the article and the data available under different licenses:

``` xml
<permissions>
  <copyright-statement>Copyright: © 2013 Baird AH et al.</copyright-statement>
  <copyright-year>2013</copyright-year>
  <license license-type="open-access"
           xlink:href="http://creativecommons.org/licenses/by/3.0/">
    <license-p>This is an open access article distributed under the terms of the
      Creative Commons Attribution Licence, which permits unrestricted use,
      distribution, and reproduction in any medium, provided the original work is
      properly cited.</license-p>
  </license>
  <license license-type="open-access"
           xlink:href="http://creativecommons.org/publicdomain/zero/1.0/">
    <license-p>Data associated with the article are available under the terms of
      the Creative Commons Zero "No rights reserved" data waiver (CC0 1.0 Public
      domain dedication).</license-p>
  </license>
</permissions>
```

I just had a gander at [the XML](http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=4314658) for a recent article, [PMC4314658](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4314658/), and I notice that the data is only referenced in a "Data Availability" section.

How should this be tagged?  Clearly, multiple &license> elements inside the topmost &lt;permissions> against our current recommendations.

**Comment by Daniel-Mietchen** [comment]
Same problem with BMC papers: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC4313467 .

**Comment by MichaelAEvans** [comment]
Hi both,

One thing to note on the F1000R example - we're going to be changing this part: '<license license-type="open-access" xlink:href="http://creativecommons.org/licenses/by/4.0/">' to this: '<license xlink:href="http://creativecommons.org/licenses/by/4.0/">'  so that will be in accordance with the recommendation.

I hadn't twigged from the recommendation page (https://github.com/JATS4R/elements/wiki/Permissions) that we could only have one of the '<license xlink:href' parts per article, but I understand this makes sense as we don't currently have a machine readable way of differentiating between different '<license xlink:href' elements.

Just one note for Chris - note you said "data is only referenced in a "Data Availability" section" - the data is also in the Widget in the article and reference list, though we don't have a citation in the widget.

Any suggestions for how we should be tagging our multiple elements?

Is there something we could borrow from the "Multiple licenses for different components" part of the recommendation?

**Comment by rupertgatti** [comment]
Might it be possible to tag the data using <supplementary-material> , which would then allow <permissions> as a child element?

**Comment by rupertgatti** [comment]
Might it be possible to tag the data using '<supplementary-material>' , which would then allow '<permissions>' as a child element?

**Comment by rupertgatti** [comment]
Might it be possible to tag the data using "supplementary-material" , which would then allow "permissions" as a child element?
